spring:
  application:
    name: feign-consumer

  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        health-check-path: /health
        health-check-interval: 5s
        ip-address: 127.0.0.1
        prefer-ip-address: true


#Fegin 连接超时

#ribbon.ReadTimeout=60000
#ribbon.ConnectTimeout=60000
#ribbon.MaxAutoRetries=0
#ribbon.MaxAutoRetriesNextServer=1

feign:
  client:
    config:
      remote-service:           #服务名，填写default为所有服务
        connectTimeout: 10000
        readTimeout: 12000




hystrix:


  metrics:
    polling-interval-ms: 5000














