server:
  port: 8081
  ssl:
#    key-store: /etc/letsencrypt/live/oumingyuan.club/keystore.p12
    key-store: classpath:static/resource/keystore.p12
    key-alias: tomcat
    enabled: true
    key-store-password: 123456
    key-store-type: PKCS12

spring:
  mail:
    # 免费邮是smtp.qq.com和pop.qq.com，也是采用SSL加密，端口号995和465。
    host: smtp.exmail.qq.com
    username: 10001011@oumingyuan.club
    password: Omy15609681930,,
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
            required: false
          ssl:
            enable: true

  application:
    name: email-service

  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        health-check-path: /health
        health-check-interval: 5s
        ip-address: 127.0.0.1
        prefer-ip-address: true